Feature/signup
shinonome-inc/backend-final-assignment-terukina pull request #1
Opened 2023-06-18 08:00 UTC by terukinayuuki

## 受講生の確認事項

- [ ] 画面をブラウザで実際に開いてテスト要件の[画面と機能](https://docs.google.com/spreadsheets/d/1tUi2xkohBzXZySmKDYruRruvlOmUV6bJK_GExeG5Tsw/edit#gid=1308498917)の動作確認をした（動作が分からない場合講師からスクリーンショットの提出を求めることがあります）
- [ ] Django Adminに，今まで作成したモデルを全て登録した
- [ ] テスト要件のテストを全て実装した
- [ ] CI が全て通った

## １次レビュアーの確認事項

- [ ] [レビューポイント](https://www.notion.so/shinonome-inc/Backend-Wiki-fc6c2fb218fd42c8a5cb3abbea93a6bd?pvs=4#236ff7ed318e48648b3649782b101498)を満たしている

2023-06-18 08:17 UTC, terukinayuuki commented
CircleCIは間違えてしまったので、無視でお願いします。
レビューよろしくお願いします。

2023-06-18 08:30 UTC, HasegawaKota commented on accounts/tests.py
>  # class TestSignupView(TestCase):
まだテストが10個くらい残ってると思いますのでそのテストもお願いします

2023-09-01 15:51 UTC, h-iwasaki083 requested changes
1点の修正と、以下の2点に関して追加をお願いします！いずれも [資料](https://playground.wraptas.site/b6ce37a837614e03b8d6eb726a3338e0) に記載がありますので、参考にして下さい👀

 

- [x] adminサイトからsuperuserがデータの作成をできるように、Userモデルをaccounts/admin.pyで登録してください。

- [x]  tweetsフォルダに書いたhomeViewに関してもテストを作成して下さい！現段階ではログインしたユーザーがホームの画面に飛べることが確認できればOKです。

2023-09-01 15:51 UTC, h-iwasaki083 commented on templates/base.html
> +  </body>
どのページからもwelcomeの画面とsignupの画面に飛べるようにしたいので、ページの上部に各urlに飛ぶボタンを作って下さい！

2023-09-10 15:10 UTC, h-iwasaki083 requested changes
主にテストに関して、数点コメントしたので再度ご確認お願いします◎

2023-09-10 15:10 UTC, h-iwasaki083 commented on templates/base.html
> +    <a href={% url "accounts:signup" %}>サインアップ</a>
修正で追加して下さったところのurlの指定の方法に関して、これでも該当するurlに飛べてはいるのですが、DTL(Django Template Language)の記法としては正確ではないので、修正をお願いします。

参考サイト：http://taustation.com/django-dtl-url/

Backend Wikiの該当箇所は以下の部分です ↓↓
<img width="862" alt="image" src="https://github.com/shinonome-inc/backend-final-assignment-terukina/assets/113806290/59f11f5e-ed48-48c7-b3af-6f4417be67c3">

2023-09-10 15:10 UTC, h-iwasaki083 commented on accounts/tests.py
> +class TestSignupView(TestCase):
test_failure_post_with_empty_formが抜けているので追加をお願いします！

2023-09-10 15:10 UTC, h-iwasaki083 commented on accounts/tests.py
> +        self.assertEqual(form.errors["password2"], ["このパスワードは一般的すぎます。", "このパスワードは数字しか使われていません。"])
"このパスワードは一般的すぎます。"というエラー文は、パスワードが数字のみであることへのエラーではなくパスワードが単純すぎることに対して起きているものなので、今回テストしたい内容には関係がないです。
本来出したいエラーもしっかり表示されているので問題はないですが、テストしたい内容を明確にするためにも、パスワードを複雑な数字の羅列にするとより望ましいと思います。

2023-09-10 15:10 UTC, h-iwasaki083 commented on accounts/tests.py
> +        self.url = reverse("tweets:home")
また、setUp以外での変数にはself.は付けなくて良いです。
selfをつけるのは、そのメソッド外でも使いたい時です。今回はこのメソッド内で使えればいいので url だけで大丈夫です。

2023-09-10 15:10 UTC, h-iwasaki083 commented on accounts/tests.py
> +class Homeview(TestCase):
テストは、テストにかけるViewを書いたアプリ内のファイルに書いてほしいので、HomeViewのテストはHomeViewを書いたtweetsアプリの中のtests.pyにお願いします◎ (コメントアウトされた記入箇所があるはず！)

2023-09-11 09:15 UTC, h-iwasaki083 requested changes
細かいですがあと2点だけご確認お願いします！

2023-09-11 09:15 UTC, h-iwasaki083 commented on templates/base.html
> +    <a href="{% url "accounts:signup" %}">サインアップ</a>
これだとそれぞれ、tweets:home と accounts:signup が文字列扱いになっていないので
tweets:home と accounts:signup はシングルクオーテーションで囲んでください！

`<a href="{% url 'tweets:home' %}">ホーム</a>`
↑↑ こんな感じです ↑↑

2023-09-11 09:15 UTC, h-iwasaki083 commented on accounts/tests.py
> +        self.assertEqual(form.errors["password2"], ["このパスワードは数字しか使われていません。"])
間違えではないですが、他のエラー文の確認はassertInを用いているのにここだけassertEqualを用いて list in list のチェックにしているのが違和感があります。
余力があればassertInを用いたテストに書き直してみてください👀

2023-09-11 11:21 UTC, h-iwasaki083 approved these changes
1点[修正抜け](https://github.com/shinonome-inc/backend-final-assignment-terukina/pull/1#discussion_r1321232848)があるのでご確認下さい！
他の部分はOKです🙆‍♀️

2023-09-14 04:30 UTC, YusukeKaneko commented
[こちら](https://github.com/shinonome-inc/backend-final-assignment-terukina/pull/1#discussion_r1321232848)だけよろしくお願いします。

2023-09-14 05:25 UTC, YusukeKaneko commented
[こちら](https://github.com/shinonome-inc/backend-final-assignment-terukina/pull/1#discussion_r1321232848)だけよろしくお願いします。

2023-09-14 08:18 UTC, YusukeKaneko approved these changes
LGTM

2023-09-14 08:18 UTC, merged